version: '3.2'

services:
 localstack:
    image: localstack/localstack
    environment:
      - SERVICES=firehose, iam, s3, secretsmanager
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_ACCESS_KEY_ID=test
      - DEFAULT_REGION=eu-west-1
    ports:
        - "4566:4566"
        - "4572:4572"
#       - "4573:4573"
#       - "4593:4593"
#       - "4584:4584"
    networks:
      - api_default

 minio:
    image: minio/minio:RELEASE.2020-03-19T21-49-00Z
    ports:
            - '9000:9000'
    volumes:
            - ./data/.minio/data:/export
            - ./data/.minio/config:/root/.minio
    environment:
            - MINIO_ACCESS_KEY=testtest
            - MINIO_SECRET_KEY=testtest
    command: server /export
    networks:
      - api_default

 dynamodb:
    image: amazon/dynamodb-local
    ports:
        - "8001:8000"
    command: ["-jar", "DynamoDBLocal.jar"]
    networks:
      - api_default

networks:
  api_default:
    external: true


