version: '3.2'

services:
 web:
  restart: always
  build: ./web
  volumes:
   - type: bind
     source: ../clients
     target: /app/clients/
  ports:
   - "8000:8000"
  env_file:
   - .env_file
  command: /usr/local/bin/gunicorn -w 2 -b :8000 app:app

 server:
  restart: always
  build: ./server
#  volumes:
# uncomment for development
#    - ./server/conf.d:/etc/nginx/conf.d
#   - ./app/static:/app/static
  ports:
   - "80:80"
  depends_on:
   - web


