version: '3.7'

services:
 web:
  restart: always
  build:
    context: ../
    dockerfile: api/web/Dockerfile
  tty: true
  ports:
   - "8000:8000"
  env_file:
   - .env.api
  networks:
    - api_images
  command: pipenv run gunicorn -w 2 -b :8000 app:app

 server:
  restart: always
  build:
    context: ../
    dockerfile: api/server/Dockerfile
  tty: true
# volumes:
##uncomment for development
#   - ./server/conf.d:/etc/nginx/conf.d
#   - ./app/static:/app/static
  ports:
   - "80:80"
  links:
   - web
  depends_on:
   - web
  networks:
    - api_images

networks:
  api_images: